### ISSUE TITLE
download Sentinel 1B descending data

### ISSUE THREAD

**Issue by niniane123** [scottstanie/sentineleof#34]
Can this tool download Sentinel 1B descending data, I have heard that this tool does not work correctly to download descending data, I would be very sorry if my question is wrong.

**Comment by scottstanie** [comment]
Hi, have you tried to download any Sentinel 1B data and had it fail? I've never had any problems with it.

Just checking two things-
1. you're aware that there has not been new Sentinel 1B data since the outage in Dec. 2021?
2. The precise orbits (POEORB) contain over 24 hours of data, so there are many ascending and many descending orbits in a single file

**Comment by niniane123** [comment]
ok,thank you very much,I think this tool is very useful
